version: 1.2
workflows:
   -  name: Dipcall
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/dipcall.wdl
   -  name: BUSCO
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/busco.wdl
   -  name: Quast
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/quast.wdl
      testParameterFiles:
        - /QC/test/s3_quast.json
   -  name: Meryl
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/meryl.wdl
   -  name: Merqury
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/merqury.wdl
   -  name: Asmgene
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/asmgene.wdl
   -  name: YakAsmStats
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak.wdl
   -  name: YakAsmStatsnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak_no_qv.wdl
   -  name: asmChrCompleteness
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/asm_chr_completeness.wdl
   -  name: Mash
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/mash.wdl
   -  name: NTSM
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/ntsm.wdl
   -  name: MaskAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/mask_assembly.wdl
   -  name: FinalizeAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/finalizeAssembly.wdl
   -  name: finalizeGenbankAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/finalizeGenbankAssembly.wdl
   -  name: findMitoContigs
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/findMitoContigs.wdl
   -  name: ReadStats
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/read_stats.wdl
      testParameterFiles:
        - /QC/test/s3_read_stats.json
   -  name: FullQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/full_qc.wdl
   -  name: StandardQC
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc.wdl
   -  name: StandardQCnoQV
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_no_qv.wdl
   -  name: StandardQCnonTrio
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_nontrio.wdl
   -  name: FilterHiFiAdapter
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/filter_hifi_adapter.wdl
   -  name: ExtractMitoContigs
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/extractMitoContigs.wdl
   -  name: dropFastaContigs
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/dropFastaContigs.wdl
   -  name: writeUnmappedReads
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/writeUnmappedReads.wdl
   -  name: fastqReadCounts
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/fastqReadCounts.wdl
      testParameterFiles:
        - /QC/test/s3_fastqReadCounts.json
   -  name: fastqReadCoverage
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/fastqReadCoverage.wdl
   -  name: TrioHifiasmAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly.wdl
   -  name: TrioHifiasmAssemblyYakInput
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly_yak_input.wdl
   -  name: TrioHifiasmAssemblyYakInputCutadapt
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_hifiasm_assembly_yak_input_cutadapt.wdl
   -  name: TrioVerkkoAssembly
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_verkko_assembly.wdl
   -  name: TrioVerkkoAssemblyScatter
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/workflows/trio_verkko_assembly_scatter.wdl
   -  name: YakNoStats
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/yak_no_stats.wdl
   -  name: YakNoStatsHiFi
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/yak_no_stats_hifi.wdl
   -  name: PhasedGFAs2Fasta
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/gfatools.wdl
   -  name: StandardQCHaploid
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/standard_qc_haploid.wdl
   -  name: Primrose
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/primrose.wdl
   -  name: Contamination
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/contamination.wdl
   -  name: MinigraphMap
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/minigraph.wdl
   -  name: MisjoinCheck
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/misjoinCheck.wdl
   -  name: snvInDelAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/snv_indel_assembly.wdl
   -  name: svAssembly
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/SV_assembly.wdl
   -  name: Guppy
      subclass: WDL
      primaryDescriptorPath: /data_processing/wdl/scatterGuppy.wdl
   -  name: BreakIntoContigs
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/break_into_contigs.wdl
   -  name: LengthFilterFasta
      subclass: WDL
      primaryDescriptorPath: /assembly/wdl/tasks/len_filter_fasta.wdl
   -  name: SepReadsByHaplotype
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/sepReadsByHaplotype.wdl
   -  name: deepVariant
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/deepvariant.wdl
   -  name: pepperMarginDeepVariant
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/pepperMarginDeepVariant.wdl
   -  name: hapDotPy
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/hapDotPy.wdl
   -  name: Merfin
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/merfin.wdl
   -  name: MerylNonTrio
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/meryl_non_trio.wdl
   -  name: applyPolish
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/applyPolish.wdl
   -  name: mergeBam
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/mergeBam.wdl
   -  name: DipcallHappyEval
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/dipcall_happy_eval.wdl
   -  name: subBamByBed
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/subBamByBed.wdl
   -  name: yakNonTrio
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/yak_non_trio.wdl
   -  name: MerquryEval
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/merqury_eval.wdl
   -  name: marginPhase
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/marginPhase.wdl
   -  name: whatsHapPhase
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/whatsHapPhase.wdl
   -  name: extractReads
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/extract_reads.wdl
   -  name: longReadAligner
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/long_read_aligner.wdl
   -  name: correctBam
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/correct_bam.wdl
   -  name: getMapQTable
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/get_mapq_table.wdl
   -  name: filterVCFDups
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/tasks/filter_dup_vcf.wdl
   -  name: phasingHomozygousV3
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/phasing_homozygous_v3.wdl
   -  name: phasingHomozygousV4
      subclass: WDL
      primaryDescriptorPath: /QC/wdl/workflows/phasing_homozygous_v4.wdl
